language: ruby

rvm:
  - 2.4.4

before_script:
  - git submodule sync
  - git submodule update --init --recursive || (rm -fr .git/config .git/modules && git submodule deinit -f . && git submodule update --init --recursive)

script: bundle exec rake compile
