name: enterprise-script-service

up:
  - ruby:
      package: shopify/shopify/shopify-ruby
      version: 2.2.3p172-shopify
  - bundler
  - submodules

commands:
  recompile:
    syntax: ""
    desc: "Compiles native extention"
    run: bin/rake clobber compile
  compile:
    syntax: ""
    desc: "Compiles native extention"
    run: bin/rake compile
  spec:
    syntax: ""
    desc: "Run specs"
    run: bin/rake spec

packages:
  - git@github.com:Shopify/dev-shopify.git
