name: enterprise-script-service

up:
  - ruby:
      version: 2.7.1
  - bundler
  - submodules

commands:
  recompile:
    syntax: ""
    desc: "Compiles native extention"
    run: bundle exec rake clobber compile
  compile:
    syntax: ""
    desc: "Compiles native extention"
    run: bundle exec rake compile
  spec:
    syntax: ""
    desc: "Run specs"
    run: bundle exec rake spec

packages:
  - git@github.com:Shopify/dev-shopify.git
