#!/usr/bin/env ruby

require 'pathname'

OUT_OF_MEMORY_EXPECTED = %w(212971.rb 212983.rb 219293.rb 227322.rb)

def expected_result?(file)
  return true if $?.success?
  return true if $?.exitstatus == 1
  return true if OUT_OF_MEMORY_EXPECTED.include?(file) && $?.termsig == 9
  false
end

pwd = Pathname.new(__FILE__).dirname
mruby = pwd.join('../ext/enterprise_script_service/mruby/bin/mruby').to_s
testdir = pwd.join('../tests/regression')

failures = false

Dir.entries(testdir).sort.each do |file|
  filepath = testdir.join(file)
  if File.file?(filepath)
    cmd = "#{mruby} #{filepath}"
    system(cmd)

    if expected_result?(file)
      puts "#{file}: all good."
    else
      failures = true

      if $?.stopped?
        puts "#{file}: Stopped (#{$?.stopsig})"
      elsif $?.signaled?
        puts "#{file}: Signaled (#{$?.termsig})"
      elsif $?.exited?
        puts "#{file}: Exited (#{$?.exitstatus})"
      else
        puts "#{file}: unknown term signal: #{$?.methods} (#{$?})"
      end
    end
  end
end

if failures
  raise "Regression tests failed"
else
  puts
  puts "Regression tests succeeded"
end
