def a
  yield
ensure
lambda { return }.call
end

lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a {} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{ return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{a a { return proc{}} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }} }}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{ return proc{ return proc{ return proc{ return proc{ return proc{ return proc{}}}}}}}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
lambda { a {a a { return proc{}} } }.call
