name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.os }}
    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
        os: ["ubuntu-22.04", "ubuntu-24.04"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 # v1.238.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: latest
          rubygems: 3.1.2

      - name: Compile
        run: bundle exec rake compile
